Icon font
hatcoders/octopost pull request #207
Opened 2023-11-20 14:22 UTC by Luiginicoletti

<details open> 
  <summary>
    <b>Feature</b>  
  </summary>

Now we can use `<Icon />` component to use the project icons, also can use the `icon` `size` and `color` to customize the the icon according to the project styleguide in autocomplete.

use `<Icon icon="Gpt" size="large" color="active" />`

![image](https://github.com/Alecell/octopost/assets/17785028/8d0247ea-f985-4f82-8e99-4ee43085ccf4)

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

Created a `iconFont.tsx` for component and a `variables.scss` where contain the variables of icons.

also created a folder that contain a icomoon fonts:

![image](https://github.com/Alecell/octopost/assets/17785028/8041d9ed-4928-486d-b7ba-adf075a8eb12)

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/Alecell/octopost/assets/17785028/b11e96d8-67f8-44d4-8d32-34a54ae4c106)

![image](https://github.com/Alecell/octopost/assets/17785028/9096f9df-a08a-4e7f-8df3-3f4090150a5c)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [ ] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

_For now, the size values are just fictitious, with small 0.75rem, normal 1rem and large 2rem.
Once we have a styleguide the automatic values will make sense._

</details>

2023-11-21 20:37 UTC, brunubarbosa commented on src/components/InputSearch/InputSearch.tsx
> +  if (isFocused || (typeof value === 'string' && value)) {
```suggestion
  if (isFocused || (typeof value === 'string')) {
```
btw pq checar se é string se value já tem essa tipagem?

2023-11-21 21:44 UTC, Luiginicoletti commented on src/components/Icon/IconFont.tsx
> +  Canva: scss.iCanva,
Resolved, thanks

2023-11-22 00:38 UTC, Luiginicoletti commented on .vscode/extensions.json
> +{
Vdd, resolvido.

2023-11-22 00:41 UTC, Alecell requested changes

2023-11-22 00:41 UTC, Alecell commented on src/pages/home/home.tsx
> +import Icon from '~components/Icon/IconFont';
Mentenha a mesma nomeclatura da pasta e do component file

```suggestion
import Icon from '~components/Icon/Icon';
```

2023-11-22 00:41 UTC, Alecell commented on src/pages/home/home.module.scss
> +@use '../../styles/global';
Não da pra usar alias aqui? Só um `~styles`?

2023-11-22 00:41 UTC, Alecell commented on src/pages/home/home.module.scss
Refatora esse arquivo pros estilos seguirem a mesma organização do html

2023-11-22 00:41 UTC, Alecell commented on src/components/Icon/iconFont.types.ts
> +  color?: 'active' | 'unActive';
Colocar as outras cores tambem

```suggestion
  color?: 'active' | 'disabled';
```

2023-11-22 00:41 UTC, Alecell commented on src/components/Icon/iconFont.module.scss
> +// colors
Oq é isso?

2023-11-22 00:41 UTC, Alecell commented on src/components/Icon/iconFont.module.scss
> +// sizes
Não não, ranca isso

2023-11-22 00:41 UTC, Alecell commented on src/components/Icon/IconFont.tsx
> +    <span className={`${IconIcons} ${IconSizes} ${iconColors} ${className}`} />
Usar o `classNames`

2023-11-22 00:41 UTC, Alecell commented on src/components/Icon/IconFont.tsx
> +  Canva: scss.iCanva,
iniciar com letra minuscula

2023-11-22 00:42 UTC, Luiginicoletti commented on src/components/InputSearch/InputSearch.module.scss
> +    width: 28.2rem;
Obg

2023-11-22 00:42 UTC, Luiginicoletti commented on src/components/InputSearch/InputSearch.spec.tsx
> +    expect(inputElement.value).toBe('Value');
Erro no pr

2023-11-22 00:43 UTC, Luiginicoletti commented on src/components/Icon/IconFont.tsx
> +  Canva: scss.iCanva,
Feito!

2023-11-22 01:12 UTC, Luiginicoletti commented on src/components/Icon/iconFont.module.scss
> +  //   src: url('icomoon.eot');
Resolvido.

2023-11-22 01:18 UTC, Luiginicoletti commented on src/components/Icon/iconFont.module.scss
> +// colors
Era um comentário, apaguei.

2023-11-22 15:44 UTC, Luiginicoletti commented on src/components/Icon/iconFont.module.scss
> +// sizes
Feito.

2023-11-22 15:49 UTC, Luiginicoletti commented on src/pages/home/home.tsx
> +import Icon from '~components/Icon/IconFont';
Feito!

2023-11-22 15:53 UTC, Luiginicoletti commented on src/components/Icon/iconFont.stories.tsx
> +// import { Story } from '@ladle/react';
Havia feito porem tava dando erro no ladle e deixei comentado, to refazendo.

2023-11-22 16:11 UTC, Luiginicoletti commented on src/components/InputSearch/InputSearch.tsx
> +  if (isFocused || (typeof value === 'string' && value)) {
Meu aconteceu um erro que subi erradamente algumas coisas no pr, mas corrigirei no lugar certo.

2023-11-22 16:12 UTC, Luiginicoletti commented on src/pages/home/home.module.scss
Ale esses arquivos não fazem parte do meu pr, subiram sem querer e ja foi corrigido.

2023-11-22 16:13 UTC, Luiginicoletti commented on src/pages/home/home.module.scss
> +@use '../../styles/global';
feito!

2023-11-22 16:17 UTC, Luiginicoletti commented on src/components/Icon/iconFont.types.ts
> +  color?: 'active' | 'unActive';
Feito!

2023-11-22 16:54 UTC, Luiginicoletti commented on src/components/Icon/IconFont.tsx
> +    <span className={`${IconIcons} ${IconSizes} ${iconColors} ${className}`} />
Feito

2023-11-22 16:57 UTC, Luiginicoletti commented
All issues are solved.

2023-11-22 21:11 UTC, aalmeida00 approved these changes

2023-11-23 14:09 UTC, Alecell requested changes

2023-11-23 14:09 UTC, Alecell commented on src/components/Icon/Icon.tsx
> +};
Mover pra um data.ts

2023-11-23 14:09 UTC, aalmeida00 requested changes
deixar minusculo

2023-11-23 14:09 UTC, aalmeida00 commented on src/components/Icon/Icon.tsx
> +  const IconSizes = size ? sizes[size] : '';
aqui tem que ficar minusculo

2023-11-23 14:11 UTC, Luiginicoletti commented on src/components/Icon/Icon.tsx
> +};
Feito

2023-11-23 14:11 UTC, aalmeida00 approved these changes

2023-11-23 14:12 UTC, Alecell approved these changes

2023-11-23 14:14 UTC, merged